### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by mschiff** [Verezano/radar_pi#7]
Hi!

It would be very usefull to have tagged releases, so the source for a specific version of th eplugin can be downloaded. Please add a release/tag for your released versions. This makes packaging a lot easier. 

I'd like to package this plugin for Gentoo Linux and for that it requires a reliable specific download URL for the releases. 

Thanks in advance!

**Comment by Verezano** [comment]
latest version now tagged "aisradar_pi-0.98"

**Comment by mschiff** [comment]
Thank you very much! When downloading sources as an archive, the git tag is added to the project name.

So now we have tarballs are called like "radar_pi-ausradar_pi-0.89.tar.gz", which is propably not what you intened ;-)

Tags should be "v0.98" for example. Would you mind that change that?

Thanks again!

**Comment by Verezano** [comment]
Hi,

Since a real radar pi was developed, I agreed to rename my pi to aisradar,
which fits the pi better. For the tag I followed the same convention as the
main program does.
Using just radar_pi might confuse people.
I'm no git wizzard ( in my day time job I have developers taking care of
those issues) so I'd rather not change the git name.
I hope you can still work with this tag.

Regards
Johan

Op woensdag 21 januari 2015 heeft mschiff <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> het volgende
geschreven:

**Comment by mschiff** [comment]
* Hannes schrieb am 24.01.15 um 12:25 Uhr:
>Hi,

Hi Hannes,

>
>Since a real radar pi was developed, I agreed to rename my pi to aisradar,
>which fits the pi better. 

Why not rename the git repo then?

>For the tag I followed the same convention as the
>main program does.

Thats fine. But the *tag* should not include the name of the repo.  
Something just like "v1.2.3" is much more appropriate because 
downloadable tarballs will always be created like 
"<reponame>-<tag>.tar.gz" for example.


>Using just radar_pi might confuse people.
>I'm no git wizzard ( in my day time job I have developers taking 
>care of those issues) so I'd rather not change the git name.
>I hope you can still work with this tag.

I can do, but its very "hackish". To have a clean solution (not only 
from a packagers POV) my advise would be to rename the repo to 
"aisradar_pi" and use tags like mentioned above.

What do you think?

-Marc

**Comment by Verezano** [comment]
Hi Marc,

I renamed the repository to AISradar_pi. I hope it does not break things at your end. Latest tag is aisradar_piv1.2
